### ISSUE TITLE
Bug em resources/views/layouts/app.blade.php

### ISSUE THREAD

**Issue by edwardoliveira** [tecnologiacmbbauru/gestaodegabinete#9]
Durante o processo de Dockerização, eu identifiquei um bug no código disponível no Github. No arquivo `resources/views/layouts/app.blade.php` a definição `_('Documentos')` tem que ser mudada para `__('Documentos)`. Veja que tem dois underscore ao invés de um. Para que se possa acessar o app tive que entrar no container e consertar essa linha (não precisei reiniciar o container).

**Comment by MartinsPaulo** [comment]
Obrigado, correção feita.
